name: "Run Container Scan on Super Mario Docker Image with Quality Gate"
 
on:
  push:
    branches:
      - main
 
env:
  VERSION: $(( $(cat version.txt) + 1 ))
  
jobs:
  
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest	
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Get Docker Image from Docker Hub
        run: |
          docker pull docker.io/diliprathod/supermario-js-gitops:${{ env.VERSION }}
          docker save -o supermariolatestdockerimage.tar docker.io/diliprathod/supermario-js-gitops:${{ env.VERSION }}
     
      # - name: Run Trivy vulnerability scanner in tarball mode
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     input: /github/workspace/supermariolatestdockerimage.tar
      #     exit-code: '1'
      #     severity: 'CRITICAL,HIGH'

      # - name: Run Trivy vulnerability scanner in tarball mode
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     scan-type: 'image'
      #     image-ref: supermariolatestdockerimage.tar
      #     exit-code: '1'
      #     severity: 'CRITICAL,HIGH'      


      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          input: ${{ github.workspace }}/supermariolatestdockerimage.tar
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
